version: '3'
services:
  kafka:
    image: wurstmeister/kafka
    container_name: "kafka"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    volumes:
      - /home/amr/instaMongo:/data/db
  neo4j:
    image: neo4j:latest
    ports:
     - "7474:7474"
     - "7687:7687"
  cassandra:
    image: cassandra:latest
    ports:
      - "7000:7000"
      - "9042:9042"
    volumes:
      - /home/amr/instaCassandra:/var/lib/cassandra