spring:
  application:
    name: insta-media

  data:
    mongodb:
      database: instaclone_media

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB # allow only images for now
      max-request-size: 20MB

file:
  upload-dir: /home/amr/insta-clone-images/
  path:
    prefix: /images

server:
  port: 8000

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
