
spring:
  application:
    name: insta-feed

  data:
    cassandra:
      keyspaceName: insta_feed
      contactPoints: localhost
      port: 9042
      schema-action: CREATE_IF_NOT_EXISTS

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            key:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
        bindings:
          momentsPostChanged:
            consumer:
              startOffset: latest
              autoCommitOffset: false
      bindings:
        momentsPostChanged:
          destination: moments.post.changed
          contentType: application/json
          group: graphService
          consumer:
            startOffset: latest
            autoCommitOffset: false

server:
  port: 8003

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey

  service:
    username: d245ef53-5ad5-4216-9c56-89fe0f8302a0
    password: ef919ae4-b893-4969-b782-57978180ad33

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic